#!/bin/bash

if [ -z "$COMPONENT_NAME" ]; then
	COMPONENT_NAME=$(git config remote.origin.url | awk -F'/' '{print $NF}' | awk -F '.git' '{print $1}' | tr '[:upper:]' '[:lower:]')
fi

echo "$0: using COMPONENT_NAME=$COMPONENT_NAME, set COMPONENT_NAME to change" >&2
