#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

COMMAND=$1

USAGE="Usage: platutils SUBCOMMAND [ ARGS ]"

if [ -z "$COMMAND" ]; then
    echo $USAGE >&2
elif [[ "$COMMAND" == "-h" || $COMMAND == "--help" ]]; then
    COMMAND=help
fi

$DIR/$COMMAND ${@:2}
STATUS=$?

if [ "$STATUS" -eq "127" ]; then
    echo "platutils: unknown subcommand $COMMAND" >&2
    exit 1
fi
exit $STATUS


